- .env
- .gitignore
- src/components/auth/LoginForm.jsx
- src/components/main/PopularPosts.jsx
- src/context/AuthContext.jsx
- src/services/api.js
#36 
- feat/local-login 머지 후 배포 환경에서 로그인/새로고침 문제 발생
- HttpOnly 쿠키로 인해 JavaScript에서 토큰 접근 불가
- 환경변수 불일치로 잘못된 API 엔드포인트 호출
- 새로고침 시 인증 상태 초기화되어 로그인 해제
- 배포 환경 API 연동 수정
- AuthContext를 API 호출 방식으로 완전 변경
- redirectUrl 처리로 새로고침 후 원래 페이지로 복귀
- 환경변수 기반 도메인 관리
> Fix : 쿠키 도메인 오류로 인한 API 연동 문제 해결 #36

- src/components/board/BoardPostHeader.jsx
- src/components/board/BoardTagShareBar.jsx
- src/components/board/PostCard.jsx
- src/components/comment/CommentItem.jsx
- src/components/community/CommunityBoardDetail.jsx
- src/components/community/CommunityBoardList.jsx
- src/hooks/useCommunityPosts.js
- src/pages/community/CommunityBoardDetailPage.jsx
- src/pages/community/CommunityPage.jsx
- src/pages/community/CommunityWritePage.jsx
- src/router/Router.jsx
- src/services/api.js
- src/services/communityApi.js
- src/services/reportApi.js
- src/utils/board.js
#38 
목록 조회
<hr>
상세 조회
<hr>
글쓰기
<hr>
- **커뮤니티 페이지 라우팅 설정** 
- `/community/:boardType` 경로로 FREE, QNA, RETROSPECT 게시판 접근 가능
- 기본 경로 `/community`는 자유게시판으로 리다이렉트
- **커뮤니티 API 연결**
- `communityApi.js`에서 게시글 CRUD 기능 구현
- 게시글 목록 조회, 상세 조회, 작성, 수정, 삭제 API 연동
- 백엔드 응답 데이터 형식에 맞춘 데이터 변환 로직 추가
- **커뮤니티 페이지 컴포넌트 구현**
- `CommunityPage.jsx`: 게시판 메인 페이지 (카테고리, 검색, 게시글 목록)
- `CommunityBoardList.jsx`: 게시글 목록 컴포넌트
- `CommunityBoardDetail.jsx`: 게시글 상세 컴포넌트
- `CommunityWritePage.jsx`: 게시글 작성/수정 페이지
- **기타 기능**
- 게시판 타입별 분류 (자유게시판, Q&A, 회고)
- 게시글 검색 및 정렬 기능
- 리액트 어렵네요... 이상한 부분 말씀해주시면 확인하고 수정하겠습니다.
> Feat: 커뮤니티 게시판 프론트 연결 #38

- vercel.json
#13 
- 배포 시 404 오류 수정
- 배포 후 테스트 예정
> Chore: Vercel 경로 설정

- src/context/AuthContext.jsx
- src/services/api.js
> Fix: 로그인 상태 유지 및 인증 에러 처리 개선 #36

- src/components/hub/HubBoardList.jsx
- src/context/AuthContext.jsx
- src/utils/hub.js
#35
과정, 기수를 User에서 추가
태그 .split(",") 으로 수정
> Refactor: 프로젝트 태그 + 과정,기수 관련 수정

- src/components/common/AlarmDropdown.jsx
- src/hooks/useAlarms.js
- src/hooks/useSSE.js
- src/services/alarmApi.js
> ex) #63 
Server-Sent Events(SSE)를 활용한 실시간 알림 기능을 구현했습니다.
**1. useSSE 커스텀 훅 신규 생성** (`src/hooks/useSSE.js`)
- SSE 연결/해제 관리
- 자동 재연결 로직 (최대 5회, 3초 간격)
- 하트비트 및 알림 이벤트 처리
- 페이지 언로드 시 서버에 연결 해제 요청
**2. useAlarms 훅 개선** (`src/hooks/useAlarms.js`)
- SSE를 통한 실시간 알림 수신 기능 추가
- `addNewAlarm` 함수로 새 알림 즉시 반영
- 중복 알림 방지 로직 추가
- API 응답 구조 변경 대응 (`alarms` → `content`)
**3. AlarmDropdown 컴포넌트 UI 개선** (`src/components/common/AlarmDropdown.jsx`)
- 헤더 액션 영역 구조 개선
> Feat: sse 연결

- src/components/dm/DMChatArea.jsx
- src/components/dm/DMChatList.jsx
- src/components/dm/DMContainer.jsx
- src/components/dm/DMMessageList.jsx
- src/components/dm/DMSidebar.jsx
- src/components/main/PopularPosts.jsx
- src/hooks/useWebSocket.js
- src/services/dmApi.js
- src/styles/components/dm/dm.css
- src/utils/date.js
> #59 
- 더미 데이터를 실제 DM API 연결로 변경
- `getDMRooms()`, `getDMMessages()`, `createDMRoom()`, `leaveDMRoom()` API 실제 연동
- API 에러 처리 및 사용자 피드백 개선
- SockJS + STOMP 프로토콜을 이용한 실시간 메시지 송수신
- 웹소켓 연결 상태 관리 및 재연결 로직
- 메시지 전송 실패 시 fallback 처리
- 쿠키 기반 인증을 통한 보안 강화
- **채팅방 목록**: 실시간 최신 메시지 및 시간 업데이트
- **환영 페이지**: 더 매력적이고 직관적인 디자인으로 개선
- **메시지 표시**: 발신자 닉네임, 에러 상태 표시 추가
- **로딩/에러 상태**: 사용자 친화적인 피드백 제공
- 개발용 세션 관리 버튼 제거
- 사용하지 않는 더미 데이터 및 코드 정리
- 일관된 에러 메시지 및 사용자 알림 처리
- dm 메인
- dm 상세
> Fix: 웹소켓 재연결

- .env
- .gitignore
- src/components/comment/CommentItem.jsx
- src/components/together/MarketBoardDetail.jsx
- src/components/together/TogetherBoardDetail.jsx
- src/components/together/TogetherBoardList.jsx
- src/components/together/TogetherPostInfo.jsx
- src/hooks/useLikeBookmark.js
- src/hooks/useTogetherPosts.js
- src/pages/community/CommunityBoardDetailPage.jsx
- src/pages/hub/HubDetailPage.jsx
- src/pages/info/InfoBoardDetailPage.jsx
- src/pages/together/TogetherBoardDetailPage.jsx
- src/pages/together/TogetherPage.jsx
- src/pages/together/TogetherWritePage.jsx
- src/router/Router.jsx
- src/services/bookmarkApi.js
- src/services/likeApi.js
- src/services/together/gatheringApi.js
- src/services/together/marketApi.js
- src/services/together/matchingApi.js
#32 
함께해요 게시판 글 목록 불러오기, 세부 정보, 글 작성, 수정 구현
좋아요 북마크 기능
**추가 구현/수정 필요** - 아직 머지하면 안됩니다.
- 현재 로그인 사용자 권한 여부 및 작성자 여부에 따른 수정/삭제 구현
- URL의 boardType 대소문자 혼용 통일
- write 페이지 gathering/write, match/write, market/write 3가지 모두 동일한 기능을 하는 것 같아 하나의 페이지로 통일
**백엔드 요구사항**
- 모든 게시글 ResponseDTO에 bookmarkCount 필요 (현재 함께해요 게시판은 추가 완료)
> Feat: 함께해요 게시판 API 연결

- src/hooks/useImageUpload.js
- src/services/imageApi.js
- src/styles/components/common/PostContent.css
- src/styles/components/editor/editor.css
#62 
TipTap 에디터에 이미지 업로드 기능 연결
업로드한 이미지 화면에 출력
> Feat: 이미지 업로드 API 연결 및 화면에 이미지 출력

- src/components/auth/LoginForm.jsx
- src/components/auth/ProfileForm.jsx
- src/components/auth/SignupForm.jsx
- src/context/AuthContext.jsx
- src/services/api.js
- src/styles/components/auth/auth.css
- src/utils/auth.js
- src/utils/tokenManager.js
#73 
- 실시간 이메일 검증 추가
- Enter 키 네비게이션 기능 구현
- 로딩 상태 UI 개선 (버튼 비활성화, 로딩 텍스트)
- 이메일 검증 로직 중복 코드 제거 (공통 유틸리티 함수 활용)
- 인라인 스타일을 CSS 모듈로 분리
- 코드 가독성 및 유지보수성 향상
- 에러 메시지 스타일 통일
> Refactor: 로그인 기능 개선 #73

- src/hooks/useLikeBookmark.js
- src/pages/together/constants.js
- src/pages/together/togetherData.js
- src/router/Router.jsx
- src/services/bookmarkApi.js
#78 
북마크 API 수정에 따른 userId 삭제 및 하드코딩 제거
> Fix: 북마크 하드코딩 제거

- src/components/auth/LoginForm.jsx
- src/context/AuthContext.jsx
- src/services/api.js
- src/services/authApi.js
#72 
로그아웃 기능과 JWT 토큰 자동 재발급 시스템을 구현하여 완전한 인증 시스템을 완성했습니다
- 로그아웃 기능 구현 
- 서버에서 refreshToken 완전 삭제
- 토큰 재발급 API 추가
- refreshToken 만료 시 적절한 에러 처리
- 자동 토큰 재발급 인터셉터 구현
-  HttpOnly 쿠키를 통한 refreshToken 관리로 XSS 공격 방지
백엔드 로그아웃/토큰 재발급 API가 쿠키 기반으로 구현된 것([BE #233](https://github.com/prgrms-aibe-devcourse/AIBE1-FinalProject-Team01-BE/pull/233))과 연동됩니다
> Feat : 로그아웃 및 토큰 재발급 기능 구현 #72

- src/styles/components/editor/editor.css
이슈없음
이미지 깨짐 관련 CSS 수정
파일 하나 수정이라 바로 배포에 붙여도 될 것 같아요
> HOTFIX: 이미지 깨짐 수정

- src/pages/auth/ProfileSetupPage.jsx
- src/styles/components/editor/editor.css
> Chore: 메인페이지 배포

- src/pages/auth/ProfileSetupPage.jsx
#13
0714 프론트엔드 배포
배포 후 확인 부탁드립니다
> Chore: 0714 프론트엔드 배포

- src/components/board/BoardPostHeader.jsx
- src/components/board/BoardTagShareBar.jsx
- src/components/hub/HubBoardDetail.jsx
- src/components/hub/HubBoardList.jsx
- src/components/hub/HubPostInfo.jsx
#110 
- 프로젝트 허브 디자인 수정
- 정보 게시판 닉네임 안나오는 부분 수정
> Refactor: 프로젝트 허브 디자인 일관성 수정

- src/components/mypage/EditProfileForm.jsx
- src/components/mypage/ProfileSummary.jsx
- src/components/mypage/StudentVerificationForm.jsx
- src/constants/topics.js
- src/pages/auth/ProfileSetupPage.jsx
- src/pages/mypage/MyPage.jsx
- src/styles/components/mypage/mypage.css
- src/utils/provider.js
#103 
토픽 선택 기능의 백엔드 연동과 수강생 인증 폼을 새롭게 구현했습니다
**토픽 선택 백엔드 동기화**
- 기존 프론트엔드 토픽 선택과 백엔드 API 연동
- 데이터 동기화 버그 수정
**수강생 인증 폼 컴포넌트**
- StudentVerificationForm 컴포넌트 구현
- 인증 사진 업로드 기능
- 과정명/기수 입력 폼
> Feat: 토픽 선택 백엔드 동기화 및 수강생 인증 폼 구현 #103

- src/components/common/NavigationBar.jsx
- src/components/main/PopularPosts.jsx
- src/components/mypage/StudentVerificationForm.jsx
- src/pages/auth/LoginPage.jsx
- src/pages/auth/OAuthCallbackPage.jsx
- src/pages/auth/ProfileSetupPage.jsx
- src/pages/auth/SignupPage.jsx
- src/pages/community/CommunityBoardDetailPage.jsx
- src/pages/community/CommunityPage.jsx
- src/pages/community/CommunityWritePage.jsx
- src/pages/dm/DMPage.jsx
- src/pages/hub/HubDetailPage.jsx
- src/pages/hub/HubPage.jsx
- src/pages/hub/HubWritePage.jsx
- src/pages/info/InfoBoardDetailPage.jsx
- src/pages/info/InfoPage.jsx
- src/pages/info/InfoWritePage.jsx
- src/pages/main/MainPage.jsx
- src/pages/mypage/MyPage.jsx
- src/pages/together/TogetherBoardDetailPage.jsx
- src/pages/together/TogetherPage.jsx
- src/pages/together/TogetherWritePage.jsx
- src/router/Router.jsx
- src/services/verifyApi.js
- src/styles/components/auth/auth.css
- src/styles/components/common/NavigationBar.css
#65
- 수강생 인증 연결
- 데브코스 정보 / 기수 / 이미지 받기
- 인증 이미지를 통해 백엔드와 연결해서 수강생 role 업데이트
- TODO : 수강생 미인증시 수강생 인증 마크 변경
- 로그인 화면 css 수정
- 메인 화면 인기게시글 / 추천게시글 재연결
- 전체 router lazy 추가
- 인증이나 게시물 로딩 부분에서 잘못된 점이 있는지 확인 부탁드립니다!
> Feat: 수강생 인증 연결 및 리팩터링

- src/pages/together/TogetherPage.jsx
- src/router/Router.jsx
- 함께해요 게시판 라우터 오류 해결
- 병합 과정 중 잘못 들어간 내용 수정
담당 파트 확인 부탁드립니다!
> Fix: 라우터 오류 및 병합 오류 해결

- src/components/auth/LoginForm.jsx
- src/components/auth/ProfileForm.jsx
- src/services/api.js
- src/styles/components/auth/auth.css
- 로그인 오류 발생시 정확한 에러 메시지 표시
- 로그인 & 프로필 폼 에러 처리 개선
> Fix : 로그인 에러 메시지 및 프로필 폼 에러 처리 개선

- src/components/board/BoardPostHeader.jsx
- src/components/community/CommunityBoardDetail.jsx
- src/components/info/InfoBoardDetail.jsx
- src/components/together/MarketPostInfo.jsx
- src/components/together/TogetherBoardDetail.jsx
- src/components/together/TogetherPostInfo.jsx
- src/pages/community/constants.js
- src/pages/together/TogetherBoardDetailPage.jsx
- src/services/together/gatheringApi.js
- src/services/together/marketApi.js
- src/services/together/matchingApi.js
- src/styles/components/together/postinfo.css
- src/utils/board.js
#110
- Style: 각종 css 버그 수정 
- 함께해요 상태 수정 호버 추가
상태 수정 버그 있으면 바로 알려주세요
> Style: 각종 css 버그 수정 #110

- src/components/board/BoardTagShareBar.jsx
- src/components/mypage/FollowCard.jsx
- src/components/mypage/FollowList.jsx
- src/components/mypage/MyPageSidebar.jsx
- src/components/user/UserInfoModal.jsx
- src/hooks/useFollowList.js
- src/pages/mypage/MyPage.jsx
- src/services/followApi.js
- src/styles/components/mypage/followcard.css
- src/styles/components/mypage/followlist.css
> Feat: 마이페이지 팔로잉 목록 추가

- src/components/dm/DMSidebar.jsx
> ex) #133 
- + 버튼 클릭 시 팔로잉 목록 출력
- 사용자 선택 시 채팅 시작
> Feat: 채팅 시작 버튼 활성화

- src/components/board/BoardTagShareBar.jsx
- src/components/comment/CommentItem.jsx
- src/components/comment/CommentSection.jsx
- src/components/hub/HubPostInfo.jsx
- src/pages/hub/HubWritePage.jsx
- src/styles/components/comment/CommentSection.css
- src/styles/components/community/community.css
- src/styles/components/hub/hub.css
- src/utils/date.js
#137 
- 프로젝트 허브 CSS 개선
- 댓글 CSS 개선
> Style: 프로젝트 허브 및 댓글 CSS 개선 #137

- src/components/common/AlarmDropdown.jsx
- src/components/common/NavigationBar.jsx
- src/components/dm/DMContainer.jsx
- src/pages/dm/DMPage.jsx
> Feat: 알람 클릭 시 해당 페이지로 이동 구현

- src/components/main/PopularPosts.jsx
#143 
- 함께해요, 허브, 정보 게시판 연결 오류 수정
- 확인 부탁드립니다!
> Fix: 인기게시글 연결 오류 수정

- src/components/board/BoardPostHeader.jsx
- src/components/comment/CommentItem.jsx
- src/components/common/UserInfo.jsx
- src/components/mypage/EditProfileForm.jsx
- src/context/AuthContext.jsx
- src/pages/auth/ProfileSetupPage.jsx
- src/router/Router.jsx
- 자동 로그인 오류 수정
- 프로필 이미지 기본값 처리
- 소셜 로그인 후 사용자 정보 자동 입력
- 프로필 미완성 사용자 라우터 가드 구현
> Fix: 인증 관련 이슈 통합 수정

- package-lock.json
- package.json
- src/App.jsx
- src/components/common/MicroInteractions.jsx
- src/components/common/PageTransition.jsx
- src/components/common/ScrollAnimations.jsx
- src/components/common/SharedElementTransition.jsx
- src/main.jsx
- src/pages/community/CommunityPage.jsx
- src/router/Router.jsx
- src/styles/scrollbar.css
#152
- 페이지 전환 애니메이션 추가
- 항상 로그인 페이지로 리다이렉트되던거 수정
> Refactor: 페이지 전환 UX 개선 #152

- src/components/dm/DMChatArea.jsx
- src/components/dm/DMContainer.jsx
- src/components/dm/DMSidebar.jsx
> Fix: 채팅창 이슈 해결

- src/components/user/UserInfoModal.jsx
> Feat: 채팅방 이동 추가

- src/components/board/BoardPostHeader.jsx
> Refactor: 게시글 상세정보 시간 수정

- src/App.jsx
- src/components/common/NavigationBar.jsx
- src/components/main/MainStatusSection.jsx
- src/components/mypage/WithdrawPage.jsx
- src/pages/auth/ProfileSetupPage.jsx
- src/router/Router.jsx
소셜 로그인 사용자 프로필 완성 강제 기능 구현 및 사용자 경험 개선
- 소셜 가입자 프로필 완성 강제 기능
- 라우터 권한 검증 개선
- 로그아웃 / 회원탈퇴 시 사용자 경험 개선
> Fix: 소셜 로그인 사용자 프로필 완성 강제 기능 및 UX 개선

- src/components/mypage/FollowCard.jsx
> Design: 기본이미지 수정
